#!/bin/sh
pluginpath="$(dirname "$(readlink -f $0)")"

for cur in google-chrome chromium; do
    cat $pluginpath/chrome-*/Custom.css > "$HOME/.config/$cur/Default/User StyleSheets/Custom.css"
done

ln -svf $pluginpath/dircolors/dircolors.256dark "$HOME/.dircolors"
ln -svf $pluginpath/vim.pre "$HOME/.vim/bundle/theme"
ln -svf $pluginpath/vim.post "$HOME/.vim/bundle/theme"
