#!/bin/sh
pluginpath="$(dirname "$(readlink -f $0)")"

for cur in google-chrome chromium; do
    cat $pluginpath/chrome-*/Custom.css > "$HOME/.config/$cur/Default/User StyleSheets/Custom.css"
done

ln -svf $pluginpath/dircolors/dircolors.256dark "$HOME/.dircolors"
ln -svf $pluginpath/vim "$HOME/.vim/bundle/theme"

mkdir -pv "$HOME/.fonts"
ln -vf "$pluginpath/Inconsolata-dz-Powerline.otf" "$HOME/.fonts"
fc-cache
